### ISSUE TITLE
keypress stuck on resume from sleep

### ISSUE THREAD

**Issue by cubiq** [kiibohd/controller#75]
OS: Arch Linux
Keyboard: WhiteFox

How to replicate: Put the computer to sleep. Wake the computer pressing the PC power button.

Result: The controller keeps repeating the first key you press when resuming from sleep. Pressing a second key stops the stuck key and the keyboard starts working as expected.

Not completely deterministic. I'd say it happens 50% of the times.

**Comment by cubiq** [comment]
today "DEL" key got stuck and deleted a bunch on emails by accident!

this seems a pretty critical issue...

**Comment by haata** [comment]
:/

Hmm, I had to do something similar for a capsense controller I did a long
time ago. Basically, ignoring any keypresses being pressed while turning on.

Question, do you have LEDs in that keyboard? i.e. are the LEDs on during
sleep mode? (trying to figure out what sort of state the keyboard is in).

**Comment by cubiq** [comment]
no LEDs, I can add a couple just to check

**Comment by haata** [comment]
I recently added code to deal with changes in USB power state (though I
haven't pushed them to the configurator yet, needed to get more runtime on
it). So I may be able to use these hooks to deal with this problem. Having
the leds will be a good way to visually indicate the modes.
Thanks.

**Comment by cubiq** [comment]
okay so I installed LEDs. This is pretty weird and don't know if it is intended behavior, but anyway backlight stays lit when the PC goes to sleep. Also I can keep altering LED brightness with the key combo I programmed (FN2+page up/down) when the PC is asleep.

So LEDs don't seem to help with this issue.

**Comment by intafon** [comment]
I think I actually ran into this issue on my KType yesterday a couple of times. Not sure if it was waking from sleep now, but I did have delete key stuck issues which required unplugging and plugging the keyboard.
(macbook pro, retina 15 inch, late 2013, keyboard connected via thunderbolt monitor usb port)

**Comment by haata** [comment]
On macOS, I have an open bug related to HID IDLE timeouts (not defined on other OSs, usually).

Most of the issues should be fixed with https://github.com/kiibohd/controller/commit/a9e8619037bde4d27ca11303605a4957054bd872 though.

**Comment by haata** [comment]
I've implemented this fix for HID IDLE timeouts https://github.com/kiibohd/controller/commit/cb040718ae8af8272e2bb30791f4186f4a25c74f

**Comment by rwade628** [comment]
Not sure if I should open a new issue, but I'm still seeing this on my K-Type running v0.5.3

**Comment by PandorasFox** [comment]
I'm also still seeing this on my Nightfox
